spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true


logging:
  level:
    root: info
    learn.dodrde : debug
    org.springframework.security: debug